// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpfcmd

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadClaudeCmd returns the embedded CollectionSpec for claudeCmd.
func loadClaudeCmd() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ClaudeCmdBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load claudeCmd: %w", err)
	}

	return spec, err
}

// loadClaudeCmdObjects loads claudeCmd and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*claudeCmdObjects
//	*claudeCmdPrograms
//	*claudeCmdMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadClaudeCmdObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadClaudeCmd()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// claudeCmdSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claudeCmdSpecs struct {
	claudeCmdProgramSpecs
	claudeCmdMapSpecs
	claudeCmdVariableSpecs
}

// claudeCmdProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claudeCmdProgramSpecs struct {
	TpExecve   *ebpf.ProgramSpec `ebpf:"tp_execve"`
	TpExecveat *ebpf.ProgramSpec `ebpf:"tp_execveat"`
	TpOpenat   *ebpf.ProgramSpec `ebpf:"tp_openat"`
	TpOpenat2  *ebpf.ProgramSpec `ebpf:"tp_openat2"`
}

// claudeCmdMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claudeCmdMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// claudeCmdVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claudeCmdVariableSpecs struct {
}

// claudeCmdObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadClaudeCmdObjects or ebpf.CollectionSpec.LoadAndAssign.
type claudeCmdObjects struct {
	claudeCmdPrograms
	claudeCmdMaps
	claudeCmdVariables
}

func (o *claudeCmdObjects) Close() error {
	return _ClaudeCmdClose(
		&o.claudeCmdPrograms,
		&o.claudeCmdMaps,
	)
}

// claudeCmdMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadClaudeCmdObjects or ebpf.CollectionSpec.LoadAndAssign.
type claudeCmdMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *claudeCmdMaps) Close() error {
	return _ClaudeCmdClose(
		m.Events,
	)
}

// claudeCmdVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadClaudeCmdObjects or ebpf.CollectionSpec.LoadAndAssign.
type claudeCmdVariables struct {
}

// claudeCmdPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadClaudeCmdObjects or ebpf.CollectionSpec.LoadAndAssign.
type claudeCmdPrograms struct {
	TpExecve   *ebpf.Program `ebpf:"tp_execve"`
	TpExecveat *ebpf.Program `ebpf:"tp_execveat"`
	TpOpenat   *ebpf.Program `ebpf:"tp_openat"`
	TpOpenat2  *ebpf.Program `ebpf:"tp_openat2"`
}

func (p *claudeCmdPrograms) Close() error {
	return _ClaudeCmdClose(
		p.TpExecve,
		p.TpExecveat,
		p.TpOpenat,
		p.TpOpenat2,
	)
}

func _ClaudeCmdClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed claudecmd_bpfel.o
var _ClaudeCmdBytes []byte
